### ISSUE TITLE
soft label问题

### ISSUE THREAD

**Issue by zzy99** [vtddggg/training_template_for_AI_challenger_sea8#1]
你好，我看给的label.npy是float形式，然后train.py代码里的normalize和KLDivLoss也间接说明了可以接受soft label的输入，但是训练过程中它直接argmax成hard label了。这个意思是比赛其实不能用soft label吗？

**Comment by vtddggg** [comment]
argmax是为了计算准确率，loss计算还是用soft label哈

**Comment by zzy99** [comment]
抱歉，是我没仔细看orz
