### ISSUE TITLE
QA

### ISSUE THREAD

**Issue by Haidong-Kang** [vtddggg/training_template_for_AI_challenger_sea8#2]
有一个疑问，就是这个比赛我们到底要做什么，是要改造data.npy让resnet和densnet分类最高，然后同时也在B测试集上分类也最高吗？你们用的训练代码和这个train.py是一样的吗？这个B测试集是经过对抗干扰以后的吗？我们是要提高模型的鲁棒性还是什么？谢谢

**Comment by vtddggg** [comment]
请仔细阅读赛题描述，您的问题都能在规则里找到答案～谢谢
